name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
    - name: Restore Packages
      run: nuget restore steamBackup.sln
    - name: Build
      run: msbuild steamBackup.sln
